# Generated by Django 3.2.2 on 2021-06-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_commonhealthproblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonhealthproblem',
            name='image',
            field=models.ImageField(upload_to='media/problem'),
        ),
    ]
