# Generated by Django 3.2.2 on 2021-06-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_commonhealthproblem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonhealthproblem',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
