# Generated by Django 3.2.2 on 2021-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_commonhealthproblem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonhealthproblem',
            name='slug',
            field=models.CharField(default='a', max_length=200),
        ),
    ]
