# Generated by Django 3.2.2 on 2021-06-18 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('hospitalname', models.CharField(max_length=50)),
                ('hospitalcity', models.CharField(max_length=50)),
                ('hospitalarea', models.CharField(max_length=50)),
                ('onlinefees', models.CharField(max_length=50)),
                ('feesatclinic', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='doctor/')),
            ],
        ),
    ]
