# Generated by Django 3.2.2 on 2021-06-18 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_remove_doctor_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctorid',
            field=models.UUIDField(default=uuid.UUID('a45bd3a9-8867-4f5a-b8f4-cb2e62cdf5e2'), editable=False),
        ),
    ]
