# Generated by Django 3.2.2 on 2021-06-18 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_doctorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
