# Generated by Django 3.2.2 on 2021-06-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctor_doctorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='surname',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
    ]
