# Generated by Django 3.2.2 on 2021-06-19 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_doctor_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='surname',
        ),
    ]
